=== DirkMahler/sze/src/test/resources/net/sf/sze/checkberry/db/sze-db.dtd
<!ELEMENT dataset (
    INCLUDE*,
    EMPTY_TABLE*,
    ARBEITSGRUPPE*,
    ARBEITS_UND_SOZIAL_VERHALTEN*,
    BEMERKUNGS_BAUSTEIN*,
    DATABASECHANGELOG*,
    DATABASECHANGELOGLOCK*,
    GSEC_PERMISSION*,
    GSEC_ROLE*,
    GSEC_ROLE_PERMISSIONS*,
    GSEC_USER*,
    GSEC_USER_PERMISSIONS*,
    GSEC_USER_ROLES*,
    KLASSE*,
    SCHUELER*,
    SCHULAMT*,
    SCHULAMTS_BEMERKUNGS_BAUSTEIN*,
    SCHULFACH*,
    SCHULHALBJAHR*,
    SOLBEWERTUNGS_TEXT*,
    VERSION_HISTORY*,
    ZEUGNIS_ART*,
    ZEUGNIS_FORMULAR*,
    SCHULFACH_DETAIL_INFO*,
    ZEUGNIS*,
    AG_BEWERTUNG*,
    AV_SV_BEWERTUNG*,
    BEMERKUNG*,
    BEWERTUNG*,
    SCHULAMTS_BEMERKUNG*)>

<!ELEMENT INCLUDE EMPTY>
<!ATTLIST INCLUDE
    FILE CDATA #REQUIRED
    LOCATION (RELATIVE|ABSOLUTE|CLASSPATH) "RELATIVE"
>

<!ELEMENT EMPTY_TABLE EMPTY>
<!ATTLIST EMPTY_TABLE
    TABLENAME (ARBEITSGRUPPE|ARBEITS_UND_SOZIAL_VERHALTEN|BEMERKUNGS_BAUSTEIN|DATABASECHANGELOG|DATABASECHANGELOGLOCK|GSEC_PERMISSION|GSEC_ROLE|GSEC_ROLE_PERMISSIONS|GSEC_USER|GSEC_USER_PERMISSIONS|GSEC_USER_ROLES|KLASSE|SCHUELER|SCHULAMT|SCHULAMTS_BEMERKUNGS_BAUSTEIN|SCHULFACH|SCHULHALBJAHR|SOLBEWERTUNGS_TEXT|VERSION_HISTORY|ZEUGNIS_ART|ZEUGNIS_FORMULAR|SCHULFACH_DETAIL_INFO|ZEUGNIS|AG_BEWERTUNG|AV_SV_BEWERTUNG|BEMERKUNG|BEWERTUNG|SCHULAMTS_BEMERKUNG) #REQUIRED
>

<!ELEMENT ARBEITSGRUPPE EMPTY>
<!ATTLIST ARBEITSGRUPPE
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    KLASSENSTUFEN CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SORTIERUNG CDATA #REQUIRED
>

<!ELEMENT ARBEITS_UND_SOZIAL_VERHALTEN EMPTY>
<!ATTLIST ARBEITS_UND_SOZIAL_VERHALTEN
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    KLASSENSTUFEN CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SORTIERUNG CDATA #REQUIRED
    TYP CDATA #REQUIRED
>

<!ELEMENT BEMERKUNGS_BAUSTEIN EMPTY>
<!ATTLIST BEMERKUNGS_BAUSTEIN
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    AKTIV CDATA #REQUIRED
    NAME CDATA #REQUIRED
    TEXT CDATA #REQUIRED
>

<!ELEMENT DATABASECHANGELOG EMPTY>
<!ATTLIST DATABASECHANGELOG
    ID CDATA #REQUIRED
    AUTHOR CDATA #REQUIRED
    FILENAME CDATA #REQUIRED
    DATEEXECUTED CDATA #REQUIRED
    ORDEREXECUTED CDATA #REQUIRED
    EXECTYPE CDATA #REQUIRED
    MD5SUM CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    COMMENTS CDATA #IMPLIED
    TAG CDATA #IMPLIED
    LIQUIBASE CDATA #IMPLIED
>

<!ELEMENT DATABASECHANGELOGLOCK EMPTY>
<!ATTLIST DATABASECHANGELOGLOCK
    ID CDATA #REQUIRED
    LOCKED CDATA #REQUIRED
    LOCKGRANTED CDATA #IMPLIED
    LOCKEDBY CDATA #IMPLIED
>

<!ELEMENT GSEC_PERMISSION EMPTY>
<!ATTLIST GSEC_PERMISSION
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    ACTIONS CDATA #REQUIRED
    NAME CDATA #REQUIRED
    TARGET CDATA #REQUIRED
    TYPE CDATA #REQUIRED
>

<!ELEMENT GSEC_ROLE EMPTY>
<!ATTLIST GSEC_ROLE
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    NAME CDATA #REQUIRED
>

<!ELEMENT GSEC_ROLE_PERMISSIONS EMPTY>
<!ATTLIST GSEC_ROLE_PERMISSIONS
    GSEC_ROLE_ID CDATA #REQUIRED
    GSEC_PERMISSION_ID CDATA #REQUIRED
>

<!ELEMENT GSEC_USER EMPTY>
<!ATTLIST GSEC_USER
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
    EMAIL_ADRESS CDATA #IMPLIED
    ENABLED CDATA #REQUIRED
    EXPIRED_DATE CDATA #IMPLIED
    FIRSTNAME CDATA #REQUIRED
    LOGIN_FAILED_COUNT CDATA #IMPLIED
    NAME CDATA #REQUIRED
    PASSWORD_HASH CDATA #REQUIRED
    USERNAME CDATA #REQUIRED
>

<!ELEMENT GSEC_USER_PERMISSIONS EMPTY>
<!ATTLIST GSEC_USER_PERMISSIONS
    GSEC_PERMISSION_ID CDATA #REQUIRED
    GSEC_USER_ID CDATA #REQUIRED
>

<!ELEMENT GSEC_USER_ROLES EMPTY>
<!ATTLIST GSEC_USER_ROLES
    GSEC_ROLE_ID CDATA #REQUIRED
    GSEC_USER_ID CDATA #REQUIRED
>

<!ELEMENT KLASSE EMPTY>
<!ATTLIST KLASSE
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    GESCHLOSSEN CDATA #REQUIRED
    JAHRGANG CDATA #REQUIRED
    SUFFIX CDATA #REQUIRED
>

<!ELEMENT SCHUELER EMPTY>
<!ATTLIST SCHUELER
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    ABGANGS_DATUM CDATA #IMPLIED
    AUFNAHME_DATUM CDATA #IMPLIED
    GEBURTSORT CDATA #REQUIRED
    GEBURTSTAG CDATA #REQUIRED
    KLASSE_ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    NUMMER CDATA #IMPLIED
    RUFNAME CDATA #IMPLIED
    VORNAME CDATA #REQUIRED
    GESCHLECHT CDATA #REQUIRED
>

<!ELEMENT SCHULAMT EMPTY>
<!ATTLIST SCHULAMT
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    AKTIV CDATA #REQUIRED
    BESCHREIBENDER_SATZ CDATA #REQUIRED
    NAME CDATA #REQUIRED
>

<!ELEMENT SCHULAMTS_BEMERKUNGS_BAUSTEIN EMPTY>
<!ATTLIST SCHULAMTS_BEMERKUNGS_BAUSTEIN
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    AKTIV CDATA #REQUIRED
    BESCHREIBENDER_SATZ CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SORTIERUNG CDATA #REQUIRED
>

<!ELEMENT SCHULFACH EMPTY>
<!ATTLIST SCHULFACH
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SORTIERUNG CDATA #REQUIRED
    STUFEN_MIT_AUSSEN_DIFFERENZIERUNG CDATA #IMPLIED
    STUFEN_MIT_BINNEN_DIFFERENZIERUNG CDATA #IMPLIED
    STUFEN_MIT_STANDARD_BEWERTUNG CDATA #IMPLIED
    TYP CDATA #REQUIRED
>

<!ELEMENT SCHULHALBJAHR EMPTY>
<!ATTLIST SCHULHALBJAHR
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    HALBJAHR CDATA #REQUIRED
    JAHR CDATA #REQUIRED
    SELECTABLE CDATA #REQUIRED
>

<!ELEMENT SOLBEWERTUNGS_TEXT EMPTY>
<!ATTLIST SOLBEWERTUNGS_TEXT
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    NAME CDATA #REQUIRED
    TEXT CDATA #REQUIRED
>

<!ELEMENT VERSION_HISTORY EMPTY>
<!ATTLIST VERSION_HISTORY
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    APP_VERSION CDATA #REQUIRED
    INSTALL_DATE CDATA #REQUIRED
>

<!ELEMENT ZEUGNIS_ART EMPTY>
<!ATTLIST ZEUGNIS_ART
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    ABSCHLUSS_GRAD CDATA #REQUIRED
    AKTIV CDATA #REQUIRED
    NAME CDATA #REQUIRED
    NOTE_ALS_TEXT_DARSTELLEN CDATA #REQUIRED
    PLATZ_FUER_SIEGEL CDATA #REQUIRED
    PRINT_VERSETZUNGSBEMERKUNG CDATA #REQUIRED
    SORTIERUNG CDATA #REQUIRED
    TITEL CDATA #REQUIRED
>

<!ELEMENT ZEUGNIS_FORMULAR EMPTY>
<!ATTLIST ZEUGNIS_FORMULAR
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    AUSGABE_DATUM CDATA #REQUIRED
    BESCHREIBUNG CDATA #REQUIRED
    KLASSE_ID CDATA #REQUIRED
    LEITSPRUCH CDATA #IMPLIED
    LEITSPRUCH2 CDATA #IMPLIED
    NACHTEILS_AUSGLEICHS_DATUM CDATA #REQUIRED
    QUELLE_LEITSPRUCH CDATA #IMPLIED
    QUELLE_LEITSPRUCH2 CDATA #IMPLIED
    SCHULHALBJAHR_ID CDATA #REQUIRED
    TEMPLATE_FILE_NAME CDATA #REQUIRED
>

<!ELEMENT SCHULFACH_DETAIL_INFO EMPTY>
<!ATTLIST SCHULFACH_DETAIL_INFO
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    DETAIL_INFO CDATA #REQUIRED
    FORMULAR_ID CDATA #REQUIRED
    SCHULFACH_ID CDATA #REQUIRED
>

<!ELEMENT ZEUGNIS EMPTY>
<!ATTLIST ZEUGNIS
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    ANZAHL_FEHLTAGE_GESAMT CDATA #REQUIRED
    ANZAHL_FEHLTAGE_UNENTSCHULDIGT CDATA #REQUIRED
    ANZAHL_VERSPAETUNGEN CDATA #REQUIRED
    BU_BEWERTUNGS_TEXT CDATA #IMPLIED
    FORMULAR_ID CDATA #REQUIRED
    INDIVIDUELLER_LEITSPRUCH CDATA #IMPLIED
    INDIVIDUELLER_LEITSPRUCH2 CDATA #IMPLIED
    INDIVIDUELLES_AUSGABE_DATUM CDATA #IMPLIED
    KLASSE_ID CDATA #REQUIRED
    KLASSEN_ZIEL_AUSGESCHLOSSEN CDATA #REQUIRED
    KLASSEN_ZIEL_GEFAEHRDET CDATA #REQUIRED
    KLASSEN_ZIEL_WURDE_NICHT_ERREICHT CDATA #REQUIRED
    QUELLE_INDIVIDUELLER_LEITSPRUCH CDATA #IMPLIED
    QUELLE_INDIVIDUELLER_LEITSPRUCH2 CDATA #IMPLIED
    RUECKT_AUF CDATA #REQUIRED
    SCHUELER_ID CDATA #REQUIRED
    SCHULHALBJAHR_ID CDATA #REQUIRED
    SOLBEWERTUNGS_TEXT_ID CDATA #IMPLIED
    ZEUGNIS_ART_ID CDATA #REQUIRED
>

<!ELEMENT AG_BEWERTUNG EMPTY>
<!ATTLIST AG_BEWERTUNG
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    ARBEITSGRUPPE_ID CDATA #REQUIRED
    TEILGENOMMEN CDATA #REQUIRED
    ZEUGNIS_ID CDATA #REQUIRED
>

<!ELEMENT AV_SV_BEWERTUNG EMPTY>
<!ATTLIST AV_SV_BEWERTUNG
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    ARBEITS_UND_SOZIAL_VERHALTEN_ID CDATA #REQUIRED
    BEURTEILUNG CDATA #IMPLIED
    ZEUGNIS_ID CDATA #REQUIRED
>

<!ELEMENT BEMERKUNG EMPTY>
<!ATTLIST BEMERKUNG
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    BAUSTEIN_ID CDATA #REQUIRED
    ER_SIE_STATT_NAMEN CDATA #REQUIRED
    FREI_TEXT CDATA #IMPLIED
    SORTIERUNG CDATA #REQUIRED
    ZEUGNIS_ID CDATA #REQUIRED
>

<!ELEMENT BEWERTUNG EMPTY>
<!ATTLIST BEWERTUNG
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    LEISTUNG_NUR_SCHWACH_AUSREICHEND CDATA #REQUIRED
    LEISTUNGSNIVEAU CDATA #IMPLIED
    NOTE CDATA #IMPLIED
    RELEVANT CDATA #REQUIRED
    SCHULFACH_ID CDATA #REQUIRED
    SONDER_NOTE CDATA #REQUIRED
    ZEUGNIS_ID CDATA #REQUIRED
    CLASS CDATA #REQUIRED
>

<!ELEMENT SCHULAMTS_BEMERKUNG EMPTY>
<!ATTLIST SCHULAMTS_BEMERKUNG
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    ER_SIE_STATT_NAMEN CDATA #REQUIRED
    FREI_TEXT CDATA #IMPLIED
    SCHULAMT_ID CDATA #REQUIRED
    SCHULAMTS_BAUSTEIN_ID CDATA #REQUIRED
    SORTIERUNG CDATA #REQUIRED
    ZEUGNIS_ID CDATA #REQUIRED
>

=== DirkMahler/sze/src/test/resources/net/sf/sze/service/impl/ZeugnisInitialisierungServiceImplIntegrationTest_testInitZeugnis_result.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset PUBLIC "-//SZE_TEAM//DTD sze-db 1.0//EN" "../../checkberry/db/sze-db.dtd">
<dataset>
  <ZEUGNIS ID="1" VERSION="0" ANZAHL_FEHLTAGE_GESAMT="0" ANZAHL_FEHLTAGE_UNENTSCHULDIGT="0" ANZAHL_VERSPAETUNGEN="0" BU_BEWERTUNGS_TEXT="" KLASSEN_ZIEL_AUSGESCHLOSSEN="false" KLASSEN_ZIEL_GEFAEHRDET="false" KLASSEN_ZIEL_WURDE_NICHT_ERREICHT="false" RUECKT_AUF="true" FORMULAR_ID="1" KLASSE_ID="1" SCHUELER_ID="1" SCHULHALBJAHR_ID="1" ZEUGNIS_ART_ID="1"/>
  <ZEUGNIS ID="2" VERSION="0" ANZAHL_FEHLTAGE_GESAMT="0" ANZAHL_FEHLTAGE_UNENTSCHULDIGT="0" ANZAHL_VERSPAETUNGEN="0" BU_BEWERTUNGS_TEXT="" KLASSEN_ZIEL_AUSGESCHLOSSEN="false" KLASSEN_ZIEL_GEFAEHRDET="false" KLASSEN_ZIEL_WURDE_NICHT_ERREICHT="false" RUECKT_AUF="true" FORMULAR_ID="1" KLASSE_ID="1" SCHUELER_ID="2" SCHULHALBJAHR_ID="1" ZEUGNIS_ART_ID="1"/>
  <AG_BEWERTUNG ID="1" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="2" ZEUGNIS_ID="1"/>
  <AG_BEWERTUNG ID="2" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="7" ZEUGNIS_ID="1"/>
  <AG_BEWERTUNG ID="3" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="2" ZEUGNIS_ID="2"/>
  <AG_BEWERTUNG ID="4" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="7" ZEUGNIS_ID="2"/>
  <AV_SV_BEWERTUNG ID="1" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="1" ZEUGNIS_ID="1"/>
  <AV_SV_BEWERTUNG ID="2" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="10" ZEUGNIS_ID="1"/>
  <AV_SV_BEWERTUNG ID="3" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="1" ZEUGNIS_ID="2"/>
  <AV_SV_BEWERTUNG ID="4" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="10" ZEUGNIS_ID="2"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.AussenDifferenzierteBewertung" ID="1" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="1" ZEUGNIS_ID="1"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.BinnenDifferenzierteBewertung" ID="2" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="2" ZEUGNIS_ID="1"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="3" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="4" ZEUGNIS_ID="1"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="4" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="false" SONDER_NOTE="" SCHULFACH_ID="12" ZEUGNIS_ID="1"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.AussenDifferenzierteBewertung" ID="5" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="1" ZEUGNIS_ID="2"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.BinnenDifferenzierteBewertung" ID="6" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="2" ZEUGNIS_ID="2"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="7" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="4" ZEUGNIS_ID="2"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="8" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="false" SONDER_NOTE="" SCHULFACH_ID="12" ZEUGNIS_ID="2"/>
</dataset>

=== DirkMahler/sze/src/test/resources/net/sf/sze/service/impl/ZeugnisInitialisierungServiceImplIntegrationTest_testInitZeugnisUpdate_result.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset PUBLIC "-//SZE_TEAM//DTD sze-db 1.0//EN" "../../checkberry/db/sze-db.dtd">
<dataset>
  <ZEUGNIS ID="#{zeugnis1}" VERSION="0" ANZAHL_FEHLTAGE_GESAMT="0" ANZAHL_FEHLTAGE_UNENTSCHULDIGT="0" ANZAHL_VERSPAETUNGEN="0" BU_BEWERTUNGS_TEXT="" KLASSEN_ZIEL_AUSGESCHLOSSEN="false" KLASSEN_ZIEL_GEFAEHRDET="false" KLASSEN_ZIEL_WURDE_NICHT_ERREICHT="false" RUECKT_AUF="true" FORMULAR_ID="1" KLASSE_ID="1" SCHUELER_ID="1" SCHULHALBJAHR_ID="1" ZEUGNIS_ART_ID="1"/>
  <ZEUGNIS ID="#{zeugnis2}" VERSION="0" ANZAHL_FEHLTAGE_GESAMT="0" ANZAHL_FEHLTAGE_UNENTSCHULDIGT="0" ANZAHL_VERSPAETUNGEN="0" BU_BEWERTUNGS_TEXT="" KLASSEN_ZIEL_AUSGESCHLOSSEN="false" KLASSEN_ZIEL_GEFAEHRDET="false" KLASSEN_ZIEL_WURDE_NICHT_ERREICHT="false" RUECKT_AUF="true" FORMULAR_ID="1" KLASSE_ID="1" SCHUELER_ID="2" SCHULHALBJAHR_ID="1" ZEUGNIS_ART_ID="1"/>
  <AG_BEWERTUNG ID="ge 0.0" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="2" ZEUGNIS_ID="#{zeugnis1}"/>
  <AG_BEWERTUNG ID="ge 0.0" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="5" ZEUGNIS_ID="#{zeugnis1}"/>
  <AG_BEWERTUNG ID="ge 0.0" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="2" ZEUGNIS_ID="#{zeugnis2}"/>
  <AG_BEWERTUNG ID="ge 0.0" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="5" ZEUGNIS_ID="#{zeugnis2}"/>
  <AV_SV_BEWERTUNG ID="ge 0.0" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="1" ZEUGNIS_ID="#{zeugnis1}"/>
  <AV_SV_BEWERTUNG ID="ge 0.0" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="10" ZEUGNIS_ID="#{zeugnis1}"/>
  <AV_SV_BEWERTUNG ID="ge 0.0" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="1" ZEUGNIS_ID="#{zeugnis2}"/>
  <AV_SV_BEWERTUNG ID="ge 0.0" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="10" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.AussenDifferenzierteBewertung" ID="19" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="E" RELEVANT="true" SONDER_NOTE="TEST" SCHULFACH_ID="1" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.BinnenDifferenzierteBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="2" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="3" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.BinnenDifferenzierteBewertung" ID="22" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="Z" RELEVANT="true" SONDER_NOTE="TEST2" SCHULFACH_ID="4" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="5" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.AussenDifferenzierteBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="6" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="false" SONDER_NOTE="" SCHULFACH_ID="13" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.BinnenDifferenzierteBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="false" SONDER_NOTE="" SCHULFACH_ID="11" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.AussenDifferenzierteBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="false" SONDER_NOTE="" SCHULFACH_ID="12" ZEUGNIS_ID="#{zeugnis1}"/>

  <BEWERTUNG CLASS="net.sf.sze.zeugnis.AussenDifferenzierteBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="1" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.BinnenDifferenzierteBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="2" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="3" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.BinnenDifferenzierteBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="4" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="5" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.AussenDifferenzierteBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="6" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="false" SONDER_NOTE="" SCHULFACH_ID="13" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.BinnenDifferenzierteBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="false" SONDER_NOTE="" SCHULFACH_ID="11" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.AussenDifferenzierteBewertung" ID="ge 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="false" SONDER_NOTE="" SCHULFACH_ID="12" ZEUGNIS_ID="#{zeugnis2}"/>
</dataset>

=== DirkMahler/sze/src/test/resources/net/sf/sze/service/impl/ZeugnisInitialisierungServiceImplIntegrationTest_testInitZeugnisErstesHalbjahr_result.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset PUBLIC "-//SZE_TEAM//DTD sze-db 1.0//EN" "../../checkberry/db/sze-db.dtd">
<dataset>
  <ZEUGNIS ID="#{zeugnis1}" VERSION="0" ANZAHL_FEHLTAGE_GESAMT="0" ANZAHL_FEHLTAGE_UNENTSCHULDIGT="0" ANZAHL_VERSPAETUNGEN="0" BU_BEWERTUNGS_TEXT="" KLASSEN_ZIEL_AUSGESCHLOSSEN="false" KLASSEN_ZIEL_GEFAEHRDET="false" KLASSEN_ZIEL_WURDE_NICHT_ERREICHT="false" RUECKT_AUF="true" FORMULAR_ID="${formularId}" KLASSE_ID="1" SCHUELER_ID="1" SCHULHALBJAHR_ID="${halbjahrId}" ZEUGNIS_ART_ID="1"/>
  <ZEUGNIS ID="#{zeugnis2}" VERSION="0" ANZAHL_FEHLTAGE_GESAMT="0" ANZAHL_FEHLTAGE_UNENTSCHULDIGT="0" ANZAHL_VERSPAETUNGEN="0" BU_BEWERTUNGS_TEXT="" KLASSEN_ZIEL_AUSGESCHLOSSEN="false" KLASSEN_ZIEL_GEFAEHRDET="false" KLASSEN_ZIEL_WURDE_NICHT_ERREICHT="false" RUECKT_AUF="true" FORMULAR_ID="${formularId}" KLASSE_ID="1" SCHUELER_ID="2" SCHULHALBJAHR_ID="${halbjahrId}" ZEUGNIS_ART_ID="1"/>
  <AG_BEWERTUNG ID="gt 0.0" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="2" ZEUGNIS_ID="#{zeugnis1}"/>
  <AG_BEWERTUNG ID="gt 0.0" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="7" ZEUGNIS_ID="#{zeugnis1}"/>
  <AG_BEWERTUNG ID="gt 0.0" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="2" ZEUGNIS_ID="#{zeugnis2}"/>
  <AG_BEWERTUNG ID="gt 0.0" VERSION="0" TEILGENOMMEN="false" ARBEITSGRUPPE_ID="7" ZEUGNIS_ID="#{zeugnis2}"/>
  <AV_SV_BEWERTUNG ID="gt 0.0" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="1" ZEUGNIS_ID="#{zeugnis1}"/>
  <AV_SV_BEWERTUNG ID="gt 0.0" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="10" ZEUGNIS_ID="#{zeugnis1}"/>
  <AV_SV_BEWERTUNG ID="gt 0.0" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="1" ZEUGNIS_ID="#{zeugnis2}"/>
  <AV_SV_BEWERTUNG ID="gt 0.0" VERSION="0" ARBEITS_UND_SOZIAL_VERHALTEN_ID="10" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.AussenDifferenzierteBewertung" ID="gt 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="1" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.BinnenDifferenzierteBewertung" ID="gt 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="2" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="gt 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="4" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="gt 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="false" SONDER_NOTE="" SCHULFACH_ID="12" ZEUGNIS_ID="#{zeugnis1}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.AussenDifferenzierteBewertung" ID="gt 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="1" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.BinnenDifferenzierteBewertung" ID="gt 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" LEISTUNGSNIVEAU="G" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="2" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="gt 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="true" SONDER_NOTE="" SCHULFACH_ID="4" ZEUGNIS_ID="#{zeugnis2}"/>
  <BEWERTUNG CLASS="net.sf.sze.zeugnis.StandardBewertung" ID="gt 0.0" VERSION="0" LEISTUNG_NUR_SCHWACH_AUSREICHEND="false" RELEVANT="false" SONDER_NOTE="" SCHULFACH_ID="12" ZEUGNIS_ID="#{zeugnis2}"/>
</dataset>

=== DirkMahler/sze/src/test/resources/net/sf/sze/service/impl/ZeugnisInitialisierungServiceImplIntegrationTest_testInitZeugnisErstesHalbjahr_initial.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset PUBLIC "-//SZE_TEAM//DTD sze-db 1.0//EN" "checkberry/db/sze-db.dtd">
<dataset>
    <INCLUDE FILE="net/sf/sze/stammdaten.xml" LOCATION="CLASSPATH" />
    <!-- TODO Funktion um Klassenalter fix zu machen. -->
    <KLASSE ID="1" GESCHLOSSEN="false" JAHRGANG="1999" SUFFIX=""
        VERSION="0" />
    <SCHUELER ID="1" VERSION="0" GEBURTSTAG="1992-06-15" GEBURTSORT="Hamburg" KLASSE_ID="1" VORNAME="ERWIN" GESCHLECHT="0" NAME="MUSTERMANN" />
    <SCHUELER ID="2" VERSION="0" GEBURTSTAG="1992-03-15" GEBURTSORT="Kiel" KLASSE_ID="1" VORNAME="ERNA" GESCHLECHT="1" NAME="MUSTERFRAU" />

    <SCHULHALBJAHR ID="1" HALBJAHR="0" SELECTABLE="true"
        VERSION="0" JAHR="2013" />
    <SCHULHALBJAHR ID="2" HALBJAHR="1" SELECTABLE="true"
        VERSION="0" JAHR="2013" />
    <ZEUGNIS_FORMULAR SCHULHALBJAHR_ID="1"
        TEMPLATE_FILE_NAME="egal" KLASSE_ID="1" ID="1" AUSGABE_DATUM="2013-01-31"
        BESCHREIBUNG="2013 erstes Halbjahr" VERSION="0"
        NACHTEILS_AUSGLEICHS_DATUM="2012-09-14" />
    <ZEUGNIS_FORMULAR ID="2" SCHULHALBJAHR_ID="2"
        TEMPLATE_FILE_NAME="egal" KLASSE_ID="1" AUSGABE_DATUM="2013-06-31"
        BESCHREIBUNG="2013 zweites Halbjahr" VERSION="0"
        NACHTEILS_AUSGLEICHS_DATUM="2012-09-14" />
</dataset>
